//! Frozen SQLite metadata schema-1 edge names. Changes require a migration.
//! Explicit mappings keep Rust renames and documentation edits out of the disk format.
use rgit_objects::ReferenceRole;

macro_rules! registry {
    ($($variant:ident => $name:literal),+ $(,)?) => {
        pub(super) const V1: &[&str] = &[$($name),+];
        pub(super) fn name(role: ReferenceRole) -> &'static str {
            match role { $(ReferenceRole::$variant => $name),+ }
        }
    };
}

registry! {
    ObjectPolicy => "object_policy",
    ManifestEntryPolicy => "manifest_entry_policy",
    ReviewPolicy => "review_policy",
    LandingPolicy => "landing_policy",
    IntegrationPolicy => "integration_policy",
    ApprovalPolicy => "approval_policy",
    ReleasePolicy => "release_policy",
    VisibilityPolicy => "visibility_policy",
    AudiencePolicy => "audience_policy",
    BlobChunk => "blob_chunk",
    ManifestEntryTarget => "manifest_entry_target",
    SnapshotRootManifest => "snapshot_root_manifest",
    SnapshotParent => "snapshot_parent",
    SnapshotMessage => "snapshot_message",
    ChangePreviousRevision => "change_previous_revision",
    ChangeTitle => "change_title",
    ChangeDescription => "change_description",
    ChangeBaseSnapshot => "change_base_snapshot",
    ChangeCurrentSnapshot => "change_current_snapshot",
    LineHeadSnapshot => "line_head_snapshot",
    LinePreviousState => "line_previous_state",
    LineTransactionOperation => "line_transaction_operation",
    SubprojectNativeProjection => "subproject_native_projection",
    SecretDevelopmentValue => "secret_development_value",
    ConflictBase => "conflict_base",
    ConflictLeft => "conflict_left",
    ConflictRight => "conflict_right",
    OperationParent => "operation_parent",
    OperationBefore => "operation_before",
    OperationAfter => "operation_after",
    OperationLinePolicy => "operation_line_policy",
    OperationLineHeadSnapshot => "operation_line_head_snapshot",
    OperationLinePreviousState => "operation_line_previous_state",
    OperationLineIntegrationPolicy => "operation_line_integration_policy",
    OperationLineApprovalPolicy => "operation_line_approval_policy",
    OperationLineReleasePolicy => "operation_line_release_policy",
    OperationLineVisibilityPolicy => "operation_line_visibility_policy",
    OperationInversePayload => "operation_inverse_payload",
    OperationPublicEnvelope => "operation_public_envelope",
    OperationPrivatePayload => "operation_private_payload",
    MarkerTarget => "marker_target",
    ReleaseSourceSnapshot => "release_source_snapshot",
    ReleaseProjectionRules => "release_projection_rules",
    ReleaseProjectionProof => "release_projection_proof",
    ReleaseProjectedRoot => "release_projected_root",
    ReleaseNotes => "release_notes",
    ReleaseBuildProvenance => "release_build_provenance",
    ReleaseArtifact => "release_artifact",
    ReleasePolicyEvidence => "release_policy_evidence",
    PolicyPreviousVersion => "policy_previous_version",
    PolicyDeclassificationRequirement => "policy_declassification_requirement",
    PolicyKeyEnvelopeSet => "policy_key_envelope_set",
    RepositoryRootPolicy => "repository_root_policy",
    RepositoryTrustedIdentity => "repository_trusted_identity",
    RepositoryBootstrapKeyEnvelopeSet => "repository_bootstrap_key_envelope_set",
    RepositoryGenesisOperation => "repository_genesis_operation",
    RepositoryInitialLineState => "repository_initial_line_state",
    IdentityPrevious => "identity_previous",
    IdentityKeyNotBefore => "identity_key_not_before",
    IdentityKeyNotAfter => "identity_key_not_after",
    IdentityActivationOperation => "identity_activation_operation",
    IdentityNotAfterOperation => "identity_not_after_operation",
    MembershipPrevious => "membership_previous",
    MembershipActivationOperation => "membership_activation_operation",
    MembershipNotAfterOperation => "membership_not_after_operation",
    ChangeRelationSource => "change_relation_source",
    ChangeRelationResult => "change_relation_result",
    ChangeRelationProvenance => "change_relation_provenance",
    ChangeRelationOperation => "change_relation_operation",
    ResolutionConflict => "resolution_conflict",
    ResolutionResult => "resolution_result",
    ResolutionProvenance => "resolution_provenance",
    EvidenceTarget => "evidence_target",
    EvidenceSnapshot => "evidence_snapshot",
    EvidenceRuleset => "evidence_ruleset",
    EvidenceRelated => "evidence_related",
    CiRunnerIdentity => "ci_runner_identity",
    CiBuildProvenance => "ci_build_provenance",
    ProjectionRulesPrevious => "projection_rules_previous",
    ProjectionSourceSnapshot => "projection_source_snapshot",
    ProjectionRules => "projection_rules",
    ProjectionAudiencePolicy => "projection_audience_policy",
    ProjectionManifest => "projection_manifest",
    BuildSnapshot => "build_snapshot",
    BuildRuleset => "build_ruleset",
    BuildIdentity => "build_identity",
    BuildInput => "build_input",
    BuildOutput => "build_output",
    ArtifactBlob => "artifact_blob",
    PayloadReference => "payload_reference",
    ViewPolicy => "view_policy",
    ViewLineState => "view_line_state",
    ViewManifest => "view_manifest",
    MigrationOldObject => "migration_old_object",
    MigrationNewObject => "migration_new_object",
    MigrationToolIdentity => "migration_tool_identity",
    RulesetPrevious => "ruleset_previous",
}
